from .mask_temporal_pool import (
    NODE_CLASS_MAPPINGS as POOL_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as POOL_NAMES,
)
from .mask_latent_expand import (
    NODE_CLASS_MAPPINGS as EXPAND_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as EXPAND_NAMES,
)
from .crop_multiple_by_mask import (
    NODE_CLASS_MAPPINGS as CROP_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as CROP_NAMES,
)
from .scale_by import (
    NODE_CLASS_MAPPINGS as SCALE_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as SCALE_NAMES,
)
from .paint_latent_mask import (
    NODE_CLASS_MAPPINGS as PAINT_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as PAINT_NAMES,
)
from .latent_context_connection import (
    NODE_CLASS_MAPPINGS as CTX_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as CTX_NAMES,
)

from .trim_to_8n1 import (
    NODE_CLASS_MAPPINGS as TRIM_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as TRIM_NAMES,
)

NODE_CLASS_MAPPINGS = {**POOL_CLASSES, **EXPAND_CLASSES, **CROP_CLASSES, **SCALE_CLASSES, **PAINT_CLASSES, **CTX_CLASSES, **TRIM_CLASSES}
NODE_DISPLAY_NAME_MAPPINGS = {**POOL_NAMES, **EXPAND_NAMES, **CROP_NAMES, **SCALE_NAMES, **PAINT_NAMES, **CTX_NAMES, **TRIM_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
